### ISSUE TITLE
how to install rnamotif2

### ISSUE THREAD

**Issue by minqing1** [grexor/rnamotifs2#4]
Dear Gregor:

I cloned the source codes of rnamotifs, but I couldn't find the installation documentation. 
so how to install rnamootifs2 ? Please help me to figure out!

Thanks!

QJ Min

**Comment by grexor** [comment]
Hi QJ Min,

sorry for the lack of docs! Will write a short document asap and ping you here again,

Cheers,
Gregor

**Comment by plachta11b** [comment]
I have got it partially working with this dockerfile
```
FROM python:2

RUN mkdir /packages

ADD ./pybio /packages/pybio
ADD ./rnamotifs2 /packages/rnamotifs2

RUN pip install pysam numpy fisher scipy sklearn

ENV PATH $PATH:/packages/rnamotifs2/bin
ENV PYTHONPATH $PYTHONPATH:/packages
WORKDIR /packages

ENTRYPOINT ["python", "/packages/rnamotifs2/bin/rnamotifs2"]
```
I did not used this package because it seems to be user unfriendly and did not fit expected purpose but it seems to be able to run.

`#echo "$$$dockerfile above$$$" > Dockerfile`
`docker build -t rnamotifs2 .`
`docker run -it rnamotifs2 -comps /comps/file`

**Comment by grexor** [comment]
Thank you for trying it out, I hope we make it much more user friendly in the future. For now it's also integrated in the expressRNA.org platform, however a standalone version which is easy to install is essential. Cheers, Gregor
